### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-doip#11]
Because of this component is relative new, the component documentation has not been added to the main documentation yet. I will do this soon.

But the component documentation itself currently contains "TODO" marker in the first two chapters "Introduction" and "Description". This should be resolved before the upcoming release 0.10.x.

**Comment by test-fullautomation** [comment]
Hi @huavanthong , @HolQue ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
